# Generated by Django 6.0.5 on 2026-06-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancy',
            old_name='move_out_date',
            new_name='moved_out_date',
        ),
    ]
