# Generated by Django 6.0.5 on 2026-06-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_move_out_date_tenancy_moved_out_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancy',
            old_name='moved_out_date',
            new_name='move_out_date',
        ),
    ]
