# Generated by Django 6.0.5 on 2026-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['parent_property', 'unit_number']},
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='property',
            new_name='parent_property',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('parent_property', 'unit_number')},
        ),
    ]
