# Generated by Django 6.0.5 on 2026-06-09 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_alter_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('PAINTING', 'Painting'), ('WINDOW', 'Window Repairs'), ('GENERAL', 'General Repairs')], max_length=30)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INPROGRESS', 'Inprogress'), ('COMPLETE', 'Complete')], db_index=True, default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintaned_unit', to='properties.unit')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
